import "./globals.css";
import { Inter } from "next/font/google";
// import Header from "./components/Headers/Header";
import Providers from "./Providers";
import DarkMode from "./elements/darkMode/DarkMode";
import AppBar from "./components/Appbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`transition duration-300 ${inter.className}`}>
      <body className="flex flex-col min-h-screen">
        <Providers>
          {/* <Header /> */}
          <AppBar />
          <DarkMode />
          <main className="bg-white dark: bg-black">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
